# Generated by Django 5.1.2 on 2024-12-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transpo', '0002_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rental_price',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='model_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2038),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default=2039, upload_to='car_images/'),
            preserve_default=False,
        ),
    ]
